// =============================================================================
// AUTO-GENERATED — DO NOT EDIT.
//
// Source: permission-contract v1.9.2
// Generated at: 2026-07-22
// Regenerate via: node scripts/codegen-ts.mjs permissions.json > src/role-permissions.ts
//
// The Permission union, PERM_SCOPE map, and ROLE_PERMISSIONS map are derived
// from the language-agnostic JSON contract. To change the platform's role →
// permission matrix, edit permissions.json in wazobiatech/permission-contract
// and re-run codegen — do not edit this file by hand.
//
// Permission naming convention: `{service}:{resource}:{action}`.
//   service  — one of: athens, mercury, muse, helios, zeta
//   resource — domain noun (project, users, posts, members, ...)
//   action   — verb (view, write, delete, manage, ...)
//
// v1.3.0 perm scopes — the resolver uses `PERM_SCOPE[perm]` to gate which
// path (platform-user vs tenant-user) is valid for a given perm:
//   self              — universal, granted implicitly (no role needed)
//   platform          — granted via ROLE_PERMISSIONS (platform-user path);
//                       cannot be bundled into a TenantRole
//   project           — granted via TenantRole (tenant-user path);
//                       cannot appear in ROLE_PERMISSIONS
//   platform/project  — valid via either path (dual-scope).
// =============================================================================

// -----------------------------------------------------------------------------
// Permission vocabulary, partitioned by scope (v1.3.0+)
// -----------------------------------------------------------------------------

/**
 * Self-scope perms — universal, granted implicitly to every authenticated
 * user. Never appear in any ROLE_PERMISSIONS entry.
 */
export const SELF_PERMISSIONS = [
  'mercury:user:read:self',
  'mercury:user:write:self',
  'mercury:user:delete:self',
  'mercury:connection:read:self',
  'mercury:connection_slack:phrase_create:self',
  'mercury:connection_oauth:initiate:self',
  'mercury:connection_oauth:complete:self',
  'mercury:connection_slack:revoke:self',
  'mercury:connection_google:revoke:self',
  'mercury:connection_imap:revoke:self',
  'mercury:connection_imap:create:self',
  'helios:tenant:switch:self',
] as const;

/**
 * Platform-scope perms — granted via ROLE_PERMISSIONS[role] (platform-user
 * path). Cannot be bundled into a TenantRole.
 */
export const PLATFORM_PERMISSIONS = [
  'athens:project:view',
  'athens:project:update',
  'athens:project:delete',
  'athens:services:enable',
  'athens:services:disable',
  'athens:team:invite',
  'athens:team:remove',
  'mercury:users:read',
  'mercury:users:write',
  'mercury:users:batch_read',
  'mercury:api_keys:create',
  'mercury:api_keys:revoke',
  'mercury:api_keys:read',
  'mercury:api_keys:manage',
  'mercury:service_clients:read',
  'mercury:auth_config:read',
  'mercury:auth_config_apple:create',
  'mercury:auth_config_apple:update',
  'mercury:auth_config_oauth:create',
  'mercury:auth_config_oauth:update',
  'mercury:auth_config_forgot_password:create',
  'mercury:auth_config_forgot_password:update',
  'mercury:auth_config_forgot_password:read',
  'mercury:connection_oauth:refresh',
  'mercury:events:consume',
  'muse:blog:create',
  'muse:blog:read',
  'muse:blog:update',
  'muse:blog:delete',
  'helios:tenant:transfer',
  'helios:members:view',
  'helios:members:invite',
  'helios:members:remove',
  'helios:roles:assign',
  'helios:roles:revoke',
  'helios:invitations:create',
  'helios:invitations:revoke',
  'helios:external:register',
  'helios:external:revoke',
  'helios:external:view',
] as const;

/**
 * Project-scope perms — granted via TenantRole (tenant-user path). Cannot
 * appear in any ROLE_PERMISSIONS entry.
 */
export const PROJECT_PERMISSIONS = [
  'muse:posts:read',
  'muse:posts:write',
  'muse:drafts:read',
  'muse:drafts:write',
  'zeta:fines:view',
  'zeta:fines:create',
  'zeta:fines:pay',
  'zeta:fines:challenge',
  'zeta:fines:assign',
  'zeta:fleet:view',
  'zeta:fleet:edit',
  'zeta:drivers:view',
  'zeta:drivers:manage',
  'zeta:reports:view',
  'zeta:billing:view',
  'zeta:billing:manage',
  'zeta:team:manage',
  'zeta:tenant:configure',
] as const;

/**
 * Dual-scope perms — valid via either the platform-user path
 * (ROLE_PERMISSIONS) or the tenant-user path (TenantRole bundle).
 */
export const DUAL_PERMISSIONS = [
  'muse:author:create',
  'muse:author:read',
  'muse:author:update',
  'muse:author:delete',
  'muse:posts:delete',
  'muse:posts:revert',
  'muse:tag:create',
  'muse:tag:read',
  'muse:tag:update',
  'muse:tag:delete',
  'muse:category:create',
  'muse:category:read',
  'muse:category:update',
  'muse:category:delete',
  'muse:redirect:create',
  'muse:redirect:read',
  'muse:redirect:update',
  'muse:redirect:delete',
  'muse:redirect:analytics',
  'muse:faq:create',
  'muse:faq:update',
  'muse:faq:delete',
] as const;

/**
 * The closed set of valid permission strings in the system.
 *
 * The union type is the precise closed set. The `Permission` exported
 * type is used everywhere callers need to gate a decision. Typos get
 * caught at compile time when assigned into ROLE_PERMISSIONS.
 */
export type SelfPermission = (typeof SELF_PERMISSIONS)[number];
export type PlatformPermission = (typeof PLATFORM_PERMISSIONS)[number];
export type ProjectPermission = (typeof PROJECT_PERMISSIONS)[number];
export type DualPermission = (typeof DUAL_PERMISSIONS)[number];
export type Permission =
  | SelfPermission
  | PlatformPermission
  | ProjectPermission
  | DualPermission;

/**
 * Perm → scope lookup, populated at module load. The two-track resolver in
 * Helios checks `PERM_SCOPE[perm]` to decide which path (platform-user vs
 * tenant-user) is valid for the perm.
 */
export const PERM_SCOPE: Record<Permission, PermScope> = {
  // self
  'mercury:user:read:self': 'self',
  'mercury:user:write:self': 'self',
  'mercury:user:delete:self': 'self',
  'mercury:connection:read:self': 'self',
  'mercury:connection_slack:phrase_create:self': 'self',
  'mercury:connection_oauth:initiate:self': 'self',
  'mercury:connection_oauth:complete:self': 'self',
  'mercury:connection_slack:revoke:self': 'self',
  'mercury:connection_google:revoke:self': 'self',
  'mercury:connection_imap:revoke:self': 'self',
  'mercury:connection_imap:create:self': 'self',
  'helios:tenant:switch:self': 'self',
  // platform
  'athens:project:view': 'platform',
  'athens:project:update': 'platform',
  'athens:project:delete': 'platform',
  'athens:services:enable': 'platform',
  'athens:services:disable': 'platform',
  'athens:team:invite': 'platform',
  'athens:team:remove': 'platform',
  'mercury:users:read': 'platform',
  'mercury:users:write': 'platform',
  'mercury:users:batch_read': 'platform',
  'mercury:api_keys:create': 'platform',
  'mercury:api_keys:revoke': 'platform',
  'mercury:api_keys:read': 'platform',
  'mercury:api_keys:manage': 'platform',
  'mercury:service_clients:read': 'platform',
  'mercury:auth_config:read': 'platform',
  'mercury:auth_config_apple:create': 'platform',
  'mercury:auth_config_apple:update': 'platform',
  'mercury:auth_config_oauth:create': 'platform',
  'mercury:auth_config_oauth:update': 'platform',
  'mercury:auth_config_forgot_password:create': 'platform',
  'mercury:auth_config_forgot_password:update': 'platform',
  'mercury:auth_config_forgot_password:read': 'platform',
  'mercury:connection_oauth:refresh': 'platform',
  'mercury:events:consume': 'platform',
  'muse:blog:create': 'platform',
  'muse:blog:read': 'platform',
  'muse:blog:update': 'platform',
  'muse:blog:delete': 'platform',
  'helios:tenant:transfer': 'platform',
  'helios:members:view': 'platform',
  'helios:members:invite': 'platform',
  'helios:members:remove': 'platform',
  'helios:roles:assign': 'platform',
  'helios:roles:revoke': 'platform',
  'helios:invitations:create': 'platform',
  'helios:invitations:revoke': 'platform',
  'helios:external:register': 'platform',
  'helios:external:revoke': 'platform',
  'helios:external:view': 'platform',
  // project
  'muse:posts:read': 'project',
  'muse:posts:write': 'project',
  'muse:drafts:read': 'project',
  'muse:drafts:write': 'project',
  'zeta:fines:view': 'project',
  'zeta:fines:create': 'project',
  'zeta:fines:pay': 'project',
  'zeta:fines:challenge': 'project',
  'zeta:fines:assign': 'project',
  'zeta:fleet:view': 'project',
  'zeta:fleet:edit': 'project',
  'zeta:drivers:view': 'project',
  'zeta:drivers:manage': 'project',
  'zeta:reports:view': 'project',
  'zeta:billing:view': 'project',
  'zeta:billing:manage': 'project',
  'zeta:team:manage': 'project',
  'zeta:tenant:configure': 'project',
  // platform/project
  'muse:author:create': 'platform/project',
  'muse:author:read': 'platform/project',
  'muse:author:update': 'platform/project',
  'muse:author:delete': 'platform/project',
  'muse:posts:delete': 'platform/project',
  'muse:posts:revert': 'platform/project',
  'muse:tag:create': 'platform/project',
  'muse:tag:read': 'platform/project',
  'muse:tag:update': 'platform/project',
  'muse:tag:delete': 'platform/project',
  'muse:category:create': 'platform/project',
  'muse:category:read': 'platform/project',
  'muse:category:update': 'platform/project',
  'muse:category:delete': 'platform/project',
  'muse:redirect:create': 'platform/project',
  'muse:redirect:read': 'platform/project',
  'muse:redirect:update': 'platform/project',
  'muse:redirect:delete': 'platform/project',
  'muse:redirect:analytics': 'platform/project',
  'muse:faq:create': 'platform/project',
  'muse:faq:update': 'platform/project',
  'muse:faq:delete': 'platform/project',
};

/** The four valid perm scopes. Mirrors the contract's `scope` enum. */
export type PermScope = 'self' | 'platform' | 'project' | 'platform/project';

/**
 * The closed set of roles. Mirrors `RoleType` in Helios's Prisma schema.
 *
 * ROLE_PERMISSIONS only contains `platform` and `platform/project`
 * perms; `self` perms are universal (granted by the resolver's Step 1),
 * and `project` perms are for tenant users via TenantRole.
 */
export const ROLES = [
  'OWNER',
  'ADMIN',
  'EDITOR',
  'VIEWER',
] as const;
export type Role = (typeof ROLES)[number];

/**
 * Static role → permission map.
 *
 * Every role lists its permissions explicitly — there is no inheritance.
 * The contract validator (scripts/validate.mjs) enforces:
 *   - `helios:tenant:switch:self` is present as a self-scope perm (universal).
 *   - `helios:tenant:transfer` is OWNER-only (platform scope).
 *   - Every role has >=1 permission.
 *   - No role references a perm outside the vocabulary.
 *   - No self or project perms in any role.
 */
export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  OWNER: [
    'athens:project:delete',
    'athens:project:update',
    'athens:project:view',
    'athens:services:disable',
    'athens:services:enable',
    'athens:team:invite',
    'athens:team:remove',
    'helios:external:register',
    'helios:external:revoke',
    'helios:external:view',
    'helios:invitations:create',
    'helios:invitations:revoke',
    'helios:members:invite',
    'helios:members:remove',
    'helios:members:view',
    'helios:roles:assign',
    'helios:roles:revoke',
    'helios:tenant:transfer',
    'mercury:api_keys:create',
    'mercury:api_keys:manage',
    'mercury:api_keys:read',
    'mercury:api_keys:revoke',
    'mercury:auth_config:read',
    'mercury:auth_config_apple:create',
    'mercury:auth_config_apple:update',
    'mercury:auth_config_forgot_password:create',
    'mercury:auth_config_forgot_password:read',
    'mercury:auth_config_forgot_password:update',
    'mercury:auth_config_oauth:create',
    'mercury:auth_config_oauth:update',
    'mercury:connection_oauth:refresh',
    'mercury:events:consume',
    'mercury:service_clients:read',
    'mercury:users:batch_read',
    'mercury:users:read',
    'mercury:users:write',
    'muse:author:create',
    'muse:author:delete',
    'muse:author:read',
    'muse:author:update',
    'muse:blog:create',
    'muse:blog:delete',
    'muse:blog:read',
    'muse:blog:update',
    'muse:category:create',
    'muse:category:delete',
    'muse:category:read',
    'muse:category:update',
    'muse:faq:create',
    'muse:faq:delete',
    'muse:faq:update',
    'muse:posts:delete',
    'muse:posts:revert',
    'muse:redirect:analytics',
    'muse:redirect:create',
    'muse:redirect:delete',
    'muse:redirect:read',
    'muse:redirect:update',
    'muse:tag:create',
    'muse:tag:delete',
    'muse:tag:read',
    'muse:tag:update',
  ],
  ADMIN: [
    'athens:project:update',
    'athens:project:view',
    'athens:services:disable',
    'athens:services:enable',
    'athens:team:invite',
    'athens:team:remove',
    'helios:external:view',
    'helios:invitations:create',
    'helios:invitations:revoke',
    'helios:members:invite',
    'helios:members:remove',
    'helios:members:view',
    'helios:roles:assign',
    'helios:roles:revoke',
    'mercury:api_keys:create',
    'mercury:api_keys:read',
    'mercury:api_keys:revoke',
    'mercury:auth_config:read',
    'mercury:auth_config_apple:create',
    'mercury:auth_config_apple:update',
    'mercury:auth_config_forgot_password:create',
    'mercury:auth_config_forgot_password:read',
    'mercury:auth_config_forgot_password:update',
    'mercury:auth_config_oauth:create',
    'mercury:auth_config_oauth:update',
    'mercury:connection_oauth:refresh',
    'mercury:events:consume',
    'mercury:service_clients:read',
    'mercury:users:read',
    'mercury:users:write',
    'muse:author:create',
    'muse:author:delete',
    'muse:author:read',
    'muse:author:update',
    'muse:blog:create',
    'muse:blog:read',
    'muse:blog:update',
    'muse:category:create',
    'muse:category:delete',
    'muse:category:read',
    'muse:category:update',
    'muse:faq:create',
    'muse:faq:delete',
    'muse:faq:update',
    'muse:posts:delete',
    'muse:posts:revert',
    'muse:redirect:analytics',
    'muse:redirect:create',
    'muse:redirect:delete',
    'muse:redirect:read',
    'muse:redirect:update',
    'muse:tag:create',
    'muse:tag:delete',
    'muse:tag:read',
    'muse:tag:update',
  ],
  EDITOR: [
    'athens:project:view',
    'mercury:api_keys:read',
    'mercury:service_clients:read',
    'mercury:users:read',
    'muse:author:create',
    'muse:author:delete',
    'muse:author:read',
    'muse:author:update',
    'muse:blog:create',
    'muse:blog:read',
    'muse:blog:update',
    'muse:category:create',
    'muse:category:read',
    'muse:category:update',
    'muse:faq:create',
    'muse:faq:delete',
    'muse:faq:update',
    'muse:posts:delete',
    'muse:posts:revert',
    'muse:redirect:create',
    'muse:redirect:read',
    'muse:redirect:update',
    'muse:tag:create',
    'muse:tag:read',
    'muse:tag:update',
  ],
  VIEWER: [
    'athens:project:view',
    'mercury:users:read',
    'mercury:api_keys:read',
    'mercury:service_clients:read',
    'muse:blog:read',
    'muse:author:read',
    'muse:tag:read',
    'muse:category:read',
    'muse:redirect:read',
  ],
} as const;

/**
 * Returns the read-only permission array for a role.
 *
 * The array is `readonly` so callers cannot accidentally mutate the
 * shared map. Spread it (`[...resolvePermissions(role)]`) if you need
 * a mutable copy.
 */
export function resolvePermissions(role: Role): readonly Permission[] {
  return ROLE_PERMISSIONS[role];
}

/**
 * `true` if `role` is granted `perm`. Used by Helios's
 * PermissionResolverService for the platform-user path (Step 2 of
 * the two-track resolver).
 */
export function roleHasPermission(role: Role, perm: Permission): boolean {
  return ROLE_PERMISSIONS[role].includes(perm);
}

/**
 * `true` if `perm` has scope `self` (universal — granted without
 * any role lookup). Used by the resolver's Step 1.
 */
export function isSelfScope(perm: Permission): boolean {
  return PERM_SCOPE[perm] === 'self';
}

/**
 * `true` if `perm` is grantable via the platform-user path (scope
 * is `platform` or `platform/project`).
 */
export function isPlatformGrantable(perm: Permission): boolean {
  const s = PERM_SCOPE[perm];
  return s === 'platform' || s === 'platform/project';
}

/**
 * `true` if `perm` is grantable via the tenant-user path (scope is
 * `project` or `platform/project`, OR scope is unknown — tenant-defined
 * perms are always grantable via TenantRole).
 */
export function isTenantGrantable(perm: Permission | string): boolean {
  if (!(perm in PERM_SCOPE)) return true; // tenant-defined perm
  const s = PERM_SCOPE[perm as Permission];
  return s === 'project' || s === 'platform/project';
}

/**
 * Type guard: returns `true` if `value` is a known Permission string.
 */
export function isPermission(value: unknown): value is Permission {
  if (typeof value !== 'string') return false;
  return value in PERM_SCOPE;
}

/**
 * Type guard: returns `true` if `value` is a known Role string.
 */
export function isRole(value: unknown): value is Role {
  return typeof value === 'string' && (ROLES as readonly string[]).includes(value);
}

