// =============================================================================
// AUTO-GENERATED — DO NOT EDIT.
//
// Source: permission-contract v1.0.0
// Generated at: 2026-06-18
// Regenerate via: node scripts/codegen-ts.mjs permissions.json > src/role-permissions.ts
//
// The Permission union and ROLE_PERMISSIONS map are derived from the
// language-agnostic JSON contract. To change the platform's role → permission
// matrix, edit permissions.json in wazobiatech/permission-contract and
// re-run codegen — do not edit this file by hand.
//
// Permission naming convention: `{service}:{resource}:{action}`.
//   service  — one of: athens, mercury, muse, helios
//   resource — domain noun (project, users, posts, members, ...)
//   action   — verb (view, write, delete, manage, ...)
// =============================================================================

// -----------------------------------------------------------------------------
// Permission vocabulary (one tuple per service)
// -----------------------------------------------------------------------------

const ATHENS_PERMISSIONS = [
  'athens:project:view',
  'athens:project:update',
  'athens:project:delete',
  'athens:services:enable',
  'athens:services:disable',
  'athens:team:invite',
  'athens:team:remove',
] as const;
const MERCURY_PERMISSIONS = [
  'mercury:users:read',
  'mercury:users:write',
  'mercury:api_keys:manage',
  'mercury:connections:read',
] as const;
const MUSE_PERMISSIONS = [
  'muse:posts:read',
  'muse:posts:write',
  'muse:posts:delete',
  'muse:drafts:read',
  'muse:drafts:write',
] as const;
const HELIOS_PERMISSIONS = [
  'helios:members:view',
  'helios:members:invite',
  'helios:members:remove',
  'helios:roles:assign',
  'helios:roles:revoke',
  'helios:invitations:create',
  'helios:invitations:revoke',
  'helios:tenant:switch',
  'helios:tenant:transfer',
] as const;

/**
 * The full set of valid permission strings in the system.
 *
 * The union type is the precise closed set. The `Permission` exported
 * type is used everywhere callers need to gate a decision. Typos get
 * caught at compile time when assigned into ROLE_PERMISSIONS.
 */
export type Permission =
  | (typeof ATHENS_PERMISSIONS)[number]
  | (typeof MERCURY_PERMISSIONS)[number]
  | (typeof MUSE_PERMISSIONS)[number]
  | (typeof HELIOS_PERMISSIONS)[number]
;

/**
 * The closed set of roles. Mirrors `RoleType` in Helios's Prisma schema.
 */
export const ROLES = [
  'OWNER',
  'ADMIN',
  'EDITOR',
  'VIEWER',
] as const;
export type Role = (typeof ROLES)[number];

/**
 * Static role → permission map.
 *
 * Every role lists its permissions explicitly — there is no inheritance.
 * The contract validator (scripts/validate.mjs) enforces:
 *   - `helios:tenant:switch` is present in every role (universal perm).
 *   - `helios:tenant:transfer` is present only in OWNER (ZIN-4714).
 *   - Every role has >=1 permission.
 *   - No role references a perm outside the vocabulary.
 */
export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  OWNER: [
    'athens:project:view',
    'athens:project:update',
    'athens:project:delete',
    'athens:services:enable',
    'athens:services:disable',
    'athens:team:invite',
    'athens:team:remove',
    'mercury:users:read',
    'mercury:users:write',
    'mercury:api_keys:manage',
    'mercury:connections:read',
    'muse:posts:read',
    'muse:posts:write',
    'muse:posts:delete',
    'muse:drafts:read',
    'muse:drafts:write',
    'helios:members:view',
    'helios:members:invite',
    'helios:members:remove',
    'helios:roles:assign',
    'helios:roles:revoke',
    'helios:invitations:create',
    'helios:invitations:revoke',
    'helios:tenant:switch',
    'helios:tenant:transfer',
  ],
  ADMIN: [
    'athens:project:view',
    'athens:project:update',
    'athens:services:enable',
    'athens:services:disable',
    'athens:team:invite',
    'mercury:users:read',
    'mercury:users:write',
    'mercury:api_keys:manage',
    'mercury:connections:read',
    'muse:posts:read',
    'muse:posts:write',
    'muse:drafts:read',
    'muse:drafts:write',
    'helios:members:view',
    'helios:members:invite',
    'helios:members:remove',
    'helios:roles:assign',
    'helios:roles:revoke',
    'helios:invitations:create',
    'helios:invitations:revoke',
    'helios:tenant:switch',
  ],
  EDITOR: [
    'athens:project:view',
    'mercury:users:read',
    'mercury:connections:read',
    'muse:posts:read',
    'muse:posts:write',
    'muse:drafts:read',
    'muse:drafts:write',
    'helios:members:view',
    'helios:tenant:switch',
  ],
  VIEWER: [
    'athens:project:view',
    'mercury:users:read',
    'mercury:connections:read',
    'muse:posts:read',
    'muse:drafts:read',
    'helios:members:view',
    'helios:tenant:switch',
  ],
} as const;

/**
 * Returns the read-only permission array for a role.
 *
 * The array is `readonly` so callers cannot accidentally mutate the
 * shared map. Spread it (`[...resolvePermissions(role)]`) if you need
 * a mutable copy.
 */
export function resolvePermissions(role: Role): readonly Permission[] {
  return ROLE_PERMISSIONS[role];
}

/**
 * `true` if `role` is granted `perm`. Used by Helios's
 * PermissionResolverService when resolving per-tenant membership rows.
 */
export function roleHasPermission(role: Role, perm: Permission): boolean {
  return ROLE_PERMISSIONS[role].includes(perm);
}

/**
 * Type guard: returns `true` if `value` is a known Permission string.
 */
export function isPermission(value: unknown): value is Permission {
  if (typeof value !== 'string') return false;
  return (
    (ATHENS_PERMISSIONS as readonly string[]).includes(value) ||
    (MERCURY_PERMISSIONS as readonly string[]).includes(value) ||
    (MUSE_PERMISSIONS as readonly string[]).includes(value) ||
    (HELIOS_PERMISSIONS as readonly string[]).includes(value)
  );
}

/**
 * Type guard: returns `true` if `value` is a known Role string.
 */
export function isRole(value: unknown): value is Role {
  return typeof value === 'string' && (ROLES as readonly string[]).includes(value);
}

